### ISSUE TITLE
Replace pyomniscidb with heavydb once HeavyDB 6.0 is released

### ISSUE THREAD

**Issue by pearu** [conda-forge/heavyai-feedstock#1]
https://github.com/conda-forge/heavyai-feedstock/blob/e15d0badf475dec550c2085ac17aa655eb1194cc/recipe/meta.yaml#L27

**Comment by tupui** [comment]
I just released `heavydb` on PyPi. https://github.com/heavyai/heavyai/pull/33 needs to go in first and then I can make a release on PyPi of `heavyai`. Once it's done I can update the feedstock.

**Comment by guilhermeleobas** [comment]
@tupui, I believe this issue is resolved. Can we close it?

**Comment by tupui** [comment]
The recipe still points to pyomniscidb no?

**Comment by guilhermeleobas** [comment]
No, it is pointing to `pyheavydb`
https://github.com/conda-forge/heavyai-feedstock/blob/aee43d6d5ad9bcd47a914ab172c18bfa2ded5ef9/recipe/meta.yaml#L27

**Comment by tupui** [comment]
Indeed, somehow I looked at the wrong repo or an older version from the UI.
